services:
  oidc-idp:
    profiles:
      - ${DOCKER_OIDC_DISABLE:-}
    # Let this container be accessible both internally and externally on the same domain.
    container_name: idp.${COMPOSE_DOMAIN}
    image: ghcr.io/geigerzaehler/oidc-provider-mock:latest
    # https://docs.docker.com/reference/compose-file/services/#command
    command:
      [
        "--port",
        "80",
        "--user-claims",
        '{"sub": "user", "email": "user@example.com", "role": ["user"]}',
        "--user-claims",
        '{"sub": "overview-editor", "email": "overview-editor@example.com", "role": ["overview-editor"]}',
        "--user-claims",
        '{"sub": "overview-viewer", "email": "overview-viewer@example.com", "role": ["overview-viewer"]}',
        "--user-claims",
        '{"sub": "overview-searcher", "email": "overview-searcher@example.com", "role": ["overview-searcher"]}',
        "--user-claims",
        '{"sub": "overview-all", "email": "overview-all@example.com", "role": ["overview-viewer", "overview-searcher"]}',
      ]
    ports:
      - "80"
    networks:
      - app
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-idp.rule=Host(`idp.${COMPOSE_DOMAIN}`)"
