services:
  api:
    profiles:
      - ${DOCKER_API_DISABLE:-}
    build: ./api
    env_file: ./api/.env.example
    # Overwrite some config from .env.example
    environment:
      DATABASE_URL: sqlite:///api.db
      DEBUG: true
    ports:
      - "8000"
    networks:
      - app
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-api.rule=Host(`api.${COMPOSE_DOMAIN}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-api.loadbalancer.server.port=8000"
