services:
  oidc-idp:
    profiles:
      - ${DOCKER_OIDC_DISABLE:-}
    # Let this container be accessible both internally and externally on the same domain.
    container_name: idp.${COMPOSE_DOMAIN}
    build:
      # https://github.com/geigerzaehler/oidc-provider-mock
      dockerfile_inline: |
        FROM python:3.13-slim-trixie
        RUN pip install --root-user-action=ignore pipx

        # https://github.com/geigerzaehler/oidc-provider-mock/blob/main/src/oidc_provider_mock/__main__.py
        ENTRYPOINT ["/usr/local/bin/pipx", "run", "oidc-provider-mock", "--host", "0.0.0.0", "--port", "80"]
    ports:
      - "80"
    networks:
      - app
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-idp.rule=Host(`idp.${COMPOSE_DOMAIN}`)"
      # - "traefik.http.services.${COMPOSE_PROJECT_NAME}-idp.loadbalancer.server.port=9400"
