# https://taskfile.dev

version: "3"

# https://taskfile.dev/usage/#env-files
dotenv: [".env.local", ".env"]

vars:
  DOCKER_COMPOSE: '{{.TASK_DOCKER_COMPOSE | default "docker compose" }}'
  COMPOSER_INSTALL_ARGS: '{{.TASK_DOCKER_COMPOSE | default "" }}'

includes:
  coding-standards: ./task/Taskfile.coding-standards.yml
  widgets:
    # https://taskfile.dev/usage/#directory-of-included-taskfile
    taskfile: ./widgets/Taskfile.yml
    dir: ./widgets

tasks:
  default:
    - task: help

  help:
    desc: Outputs this help screen
    cmds:
      - task --list
    silent: true

  compose:
    desc: Run docker compose
    cmds:
      - "{{.DOCKER_COMPOSE}} {{.TASK_ARGS}} {{.CLI_ARGS}}"

  start:
    desc: Pull images and start service
    cmds:
      - task: compose
        vars:
          TASK_ARGS: pull
      - task: compose
        vars:
          TASK_ARGS: up --detach --wait
      - task: composer
        vars:
          TASK_ARGS: install {{.COMPOSER_INSTALL_ARGS}}

  logs:
    desc: Show live logs
    cmds:
      - task: compose
        vars:
          TASK_ARGS: logs --tail=0 --follow

  shell:
    desc: Run shell command inside PHP service
    cmds:
      - task: compose
        vars:
          TASK_ARGS: exec phpfpm bash

  composer:
    desc: "Run composer, example: task {{.TASK}} -- req symfony/orm-pack"
    cmds:
      - task: compose
        vars:
          TASK_ARGS: exec phpfpm composer {{.TASK_ARGS}}

  console:
    desc: "Run Sumfony console command, example: task {{.TASK}} -- cache:clear"
    cmds:
      - task: compose
        vars:
          TASK_ARGS: exec phpfpm bin/console {{.TASK_ARGS}}

  site:update:
    desc: Update site
    deps: [start]
    cmds:
      - task: console
        vars:
          TASK_ARGS: doctrine:migrations:migrate
      - task: console
        vars:
          TASK_ARGS: cache:clear

  fixtures:load:
    desc: Load fixtures
    prompt: This will reset your database. Continue?
    cmds:
      - task: console
        vars:
          TASK_ARGS: hautelook:fixtures:load --no-interaction

  translations:extract:
    cmds:
      # We need a translation from en to en (!) (without prefix) to be able to process placeholders in en.
      - "DEFAULT_LOCALE=en task console -- translation:extract --clean --force en --prefix=''"
      - "DEFAULT_LOCALE=en task console -- translation:extract --clean --force da"
      # Mark default translations (prefixed with `__`) as “Needs work” in Danish translations
      - gsed --in-place='' 's/<target>__/<target state=\"needs-l10n\">__/' translations/*.da.*xlf
    silent: true

  build:widgets:
    desc: Build widgets for production and copy to public folder
    cmds:
      - task widgets:build

      # Copy result into public folder
      - rm -fr {{.PUBLIC_DIR}}
      # rsync is weird when it comes to including and excluding files …
      - rsync -azv {{.BUILD_DIR}} --include '*/' --include '**/*.css' --include '**/*.js' --exclude '*' --delete {{.PUBLIC_DIR}}
      - find {{.PUBLIC_DIR}} -type f
    vars:
      BUILD_DIR: widgets/static/dist/
      PUBLIC_DIR: public/widgets
