# https://taskfile.dev

version: '3'

vars:
  APP_PORT: 3000
  BASE_PATH: ''
  WIDGET_URL: 'http://localhost:{{.APP_PORT}}/{{.BASE_PATH}}'

  DOCKER_COMPOSE: '{{.TASK_DOCKER_COMPOSE | default "docker compose" }}'

tasks:
  build:
    desc: Build widget for production
    deps: [install]
    cmds:
      - rm -fr static/dist && mkdir -p static/dist
      - docker compose run --rm node npx standalone build --all --production

  build:dev:
    desc: Build widget for develoment
    deps: [install]
    cmds:
      - docker compose run --rm node npx standalone build --all

  dev:
    desc: 'Open widget dev site and start Vite dev server'
    deps: [install]
    cmds:
      # https://stackoverflow.com/a/73821896
      - docker compose run --name rpa-process-overview-widgets --rm --publish '{{.APP_PORT}}:{{.APP_PORT}}' node npm run dev -- --port {{.APP_PORT}} --host

  open:
    desc: 'Open widget dev site'
    cmds:
      - open "{{.WIDGET_URL}}"

  install:
    cmds:
      - COMPOSE_PROFILES='*' docker compose pull
      - task npm -- install
    internal: true

  npm:
    desc: 'Run npm command. Example: task {{.TASK}} -- install'
    cmds:
      - docker compose run --rm node npm {{.CLI_ARGS}}

  coding-standards:apply:
    desc: 'Apply coding standards'
    cmds:
      - task: compose
        vars:
          TASK_ARGS: run --rm prettier . --write

  coding-standards:check:
    desc: 'Apply and check coding standards'
    cmds:
      - task: coding-standards:apply
      - task: compose
        vars:
          TASK_ARGS: run --rm prettier . --check

  compose:
    desc: Run docker compose
    cmds:
      - '{{.DOCKER_COMPOSE}} {{.TASK_ARGS}} {{.CLI_ARGS}}'
    internal: true

  default:
    cmds:
      - task --list
    silent: true
