#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

# We need a translation from en to en (!) (without prefix) to be able to process placeholders in en.
DEFAULT_LOCALE=en bin/console translation:extract --clean --force en --prefix=''
DEFAULT_LOCALE=en bin/console translation:extract --clean --force da
# Mark default translations (prefixed with `__`) as “Needs work” in Danish translations
sed --in-place='' 's/<target>__/<target state=\"needs-l10n\">__/' translations/*.da.*xlf
