# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list
    silent: true

  pip:install:
    desc: Install pip
    cmds:
      - pip install --requirement requirements.txt

  pip:install:dev:
    desc: Install pip dev
    deps:
      - pip:install
    cmds:
      - pip install --requirement requirements-dev.txt

  pip:freeze:
    desc: Freeze pip
    prompt: Really frezze pip?
    cmds:
      - pip uninstall --requirement requirements.txt --requirement requirements-dev.txt --yes
      - pip install --requirement requirements.txt
      - pip freeze > requirements.txt

      - pip uninstall --requirement requirements.txt --requirement requirements-dev.txt --yes
      - pip install --requirement requirements-dev.txt
      - pip freeze > requirements-dev.txt

      - task pip:install:dev

  flake8:
    cmds:
      - flake8 {{.CLI_ARGS}}

  start:dev:
    cmds:
      - fastapi dev app/main.py

  start:prod:
    cmds:
      - fastapi run app/main.py

  fixtures:load:
    prompt: Really reset data?
    cmds:
      - rm -f database-api.db
      - python -m app.create-data

  lint:
    cmds:
      - isort app
      - ruff check app --fix
      - ruff check app
      - flake8 app
